spring.data.redis:
  host: redis
  port: 6379

app:
  notifications:
    rate-limit-rules:
      news: { window: 1d, max: 1 }
      status: { window: 1m, max: 2 }
      marketing: { window: 1h, max: 3 }